---
title: "Evolutionary Constraints on the Longevity of IgA Antibody Titers:"
subtitle: "Outline Part 1: constraint on the longevity of antibody titers in the respiratory mucosa"
author: "Cora Hirst, Susi Linderman, Carl Davis, Hasan Ahmed, Rustom Antia..."
output: html
---

```{r setup}
#install.package("here")
library(here)

#install.package("ggplot2")
library(ggplot2)

#install.package("gridExtra")
library(gridExtra)

#install.packages("tidyverse")
library(tidyverse)

#install.packages("deSolve")
library(deSolve)

#load functions
#source(here("code", "functions", "functions.R"))

```

# Objective

The goal of this document is to develop a simple model of antibody transport from the inside of the mucosal epithelium to the outside lumen of the mucosal epithelium. We would like to understand the extent to which pre-existing antibody titers from previous infections to unrelated pathogens can interfere with the transport of newly generated IgA specific to a currently infecting pathogen. 

# Model outline

Our model considers two physiological compartments: the mucosal side of the epithelium and the external lumen on the opposite side of the epithelium. We call these compartments "Mucous" and "Lumen". 

During an infection, IgA antibodies specific for the pathogen are generated in the mucous compartment and are transported via polymeric immunoglobulin receptors, pIgRs, to the lumen. We refer to the pathogen-specific antibodies in the mucous compartment as $M_s$ and the specific antibodies in the lumen compartment as $L_s$. We hypothesize that these antibodies must compete with all of the IgA remaining in the mucosa from previous infections with other pathogens, which we refer to generally as non-specific mucosal IgA, $M_{NS}$. The population of nonspecific antibodies that are transported to the lumen is referred to generally as $L_{NS}$

We can model the flux of IgA antibodies to the lumen as an ODE model of these two populations of mucosal IgA antibodies - $M_S$ and $M_{NS}$ - which compete explicitly for transport proteins, $R$. The number of specific and nonspecific antibodies on the lumenal side, $L_S$ and $L_{NS}$ respectively, depends on the rate of removal of IgA from the lumen and the rate at which the populations are transported. 

Importantly, we assume that pIgRs, $R$, are constantly being trancytosed across the epithelium at rate $r$ regardless of whether they are bound by sIgA. This gives rise to the following set of ODEs: 

$$
\frac{dM_s}{dt} = -kM_sR - d_\mu M_s
$$

$$
\frac{dL_s}{dt} = rR_s - d_L L_s
$$

$$
\frac{dM_{ns}}{dt} = -kM_{ns}R - d_\mu M_{ns}
$$

$$
\frac{dL_{ns}}{dt} = rR_{ns} - d_L L_{ns}
$$
For our receptors: 

This tracks the number of empty receptors at the basolateral surface of the epithelium. 

$$
\frac{dR_e}{dt} = 1 - k(M_s + M_{ns})R_e - rR_e
$$
This tracks the number of receptors bound to $M_s$ at the basolateral side.
$$
\frac{dR_s}{dt} = kM_sR_e - rR_s
$$
and this tracks the number of receptors bound to $M_{ns}$ at the basolateral side. 
$$
\frac{dR_{ns}}{dt} = kM_{ns}R_e - rR_{ns}
$$

If we want the number of transport proteins total to be fixed (or perhaps time-varying due only to changes in expression), we can define the number of empty receptors as 

$$
R_e = R_T(t) - R_s - R_{ns}
$$

where $R_T$ is the total number of transport proteins. 

Then, the system becomes: 

$$
\frac{dM_s}{dt} = -kM_s(R_T(t) - R_s - R_{ns}) - d_\mu M_s
$$

$$
\frac{dR_s}{dt} = kM_s(R_T(t)-R_s-R_{ns}) - rR_s
$$

$$
\frac{dL_s}{dt} = rR_s - d_L L_s
$$

$$
\frac{dM_{ns}}{dt} = -kM_{ns}(R_T(t)-R_s-R_{ns}) - d_\mu M_{ns}
$$
$$
\frac{dR_{ns}}{dt} = kM_{ns}(R_T(t)-R_s-R_{ns}) - rR_{ns}
$$

$$
\frac{dL_{ns}}{dt} = rR_{ns} - d_L L_{ns}
$$