---
title: "Evolutionary Constraints on the Longevity of IgA Antibody Titers"
subtitle: "Simulations Part 1: constraint on the longevity of antibody titers in the respiratory mucosa"
format: html
---

```{r setup}
#install.package("here")
library(here)

#install.package("ggplot2")
library(ggplot2)

#install.package("gridExtra")
library(gridExtra)

#install.packages("tidyverse")
library(tidyverse)

#install.packages("deSolve")
library(deSolve)

#install.packages("RColorBrewer")
library(RColorBrewer)

#load functions
source(here("code", "functions", "functions.R"))

#choose plotting colors
my_colors = c("darkred", "maroon", "darkblue", "forestgreen", "darkorange", "goldenrod") #choose color range
num_colors = length(my_colors) #set number of colors needed for plotting
my_colors = colorRampPalette(my_colors)(num_colors) #increase number of colors staying in color range
```

# Setting parameters

```{r set-parms}
# biological parameters for competition simulation 
t_half = c(1/12, 6/12, 1, 2, 5, 10)*365 #half lives of antibody titers in years converted to days
## for steady state Mns
  c = 0.5 #constant rate of IgA generated through time, per day
  d_mus = -log(1/2)/(t_half*365) #decay rate of antibody in the mucosa (1/days)
  
  ss_Mns = signif(c/d_mus, 1)

## for newly generated Ms
  A0 = 10^5
  r = log(10^5)/14 #exponential growth of new population
  t_p = 7 #1/2 time to peak (days)

  # dynamics of antibody responses over course of infection
  #specific antibodies during infection
  M_s = function(A0, t_p, r, d_mu, t) {(A0/(1+exp(-r*(t-t_p))))*(1/(1+exp(-d_mu*(2*t_p-t))))} #sigmoidal growth, A0 is max antibody, t_p is half the time to peak, r is initial growt


  t = seq(0,4*t_p, by = 1/24)

  m_trajectories = sapply(d_mus, function(d_mu){
    ms = sapply(t, function(time) {M_s(A0 = A0, t_p = t_p, r = r, d_mu = d_mu, t = time)})
    }) %>% cbind(t, .) %>% as.data.frame()
  colnames(m_trajectories) = c("time", t_half)
    
  ## for transport and lumen concentration
  d_l = 1/10 #1/days
  K = signif(c/d_mus[3]) #middle 
  Vmax_vec = 10^seq(1,6,1) #catalytic rate and number of enzymes, per day (every hours)


```

```{r plotting}
M_s_flux = lapply(Vmax_vec, function(Vmax){
  sapply(d_mus, function(d_mu){
    sapply(t, function (time){
      Ms = M_s(A0 = A0, t_p = t_p, r = r, d_mu = d_mu, t = time)
      flux = Ms*Vmax/(K + Mns + Ms)
    })
  })
})


```
