---
title: "Evolutionary Constraints on the Longevity of IgA Antibody Titers"
subtitle: "Outline Part 2: Rapid mucosal recall responses may be facilitated by inducible plasma cell populations"
format: html
---

```{r setup}
#install.package("here")
library(here)

#install.package("ggplot2")
library(ggplot2)

#install.package("gridExtra")
library(gridExtra)

#install.packages("tidyverse")
library(tidyverse)

#install.packages("deSolve")
library(deSolve)

#load functions
source(here("code", "functions", "functions.R"))


```

# Objective

The goal of this document is to Outline a simulation of the recall of antibody responses in the mucosa, including a population of inducible plasma cell which secrete antibody only when stimulated by antigen. We would like to determine the extent to which this mechanism can facilitate a rapid antibody response to a previously encountered antigen when the longevity of titers in the respiratory tract wane rapidly. 

# Model Outline 

## Steady state concentration of $M_{ns}$ 

There will be some minimal steady - state concentration of total IgA in the mucosa due to the generation and waning of responses to respiratory pathogens. 

The simplest ODE to describe an influx and decay of antibody into $M$, which will be $M_{ns}$, is: 

$$
\frac{dM_{ns}}{dt} = c - d_\mu M_{ns}
$$

where $c$ is a constant rate of influx of new IgA (something akin to $\frac{A_0}{\tau}$, the peak antibody generated during an infection times the number of infections per unit time) and $d_\mu$ is the decay rate. 

*At steady state, the concentration of $M_{ns} = \frac{c}{d_\mu}$.*

## Cellular Responses 

Here, we explicitly model the B cell recruitment and differentiation that gives rise to a specific antibody response during primary and secondary infections. We track the activation, proliferation, and differentiation of B cells, $B_s$, specific for some antigen. A fraction $(1-f)$ of B cells begin proliferating in the presence of infection $V=1$ at a rate $r_b$. The other fraction $f$ of B cells differentiate into antibody secreting plasma cells, $P_s$. 

$P_s$ secrete antibody at a rate $\rho$ and die at a rate of $d_\mu$. Importantly, some plasma cells differentiate into what we refer to as *quiescent plasma cells*, $P_q$, at rate $k_1$. These cells do not secrete antibody but quickly differentiate back into antibody-secreting cells at rate $k_{-1}$ upon recall responses. $P_q$ die at a rate $d_q$, where $d_q << d_\mu$. 

This gives rise to the following set of ordinary differential equations: 

$$
\frac{dB}{dt} = r_B(1-f)BV -fBV
$$
$$
\frac{dP_s}{dt} = fBV - k_1P_s - d_\mu P_s + k_{-1}P_qV
$$

$$
\frac{dP_q}{dt} = k_1P_s - k_{-1}P_qV - d_qP_q
$$

where 

$$
V(t) = 
\begin{cases}
0 & \text{if } t > t_{infection} \\
1 & \text{if } 0 < t \leq t_{infection}
\end{cases}
$$
I might need to somehow put in a delay such that $P_q$ are not immediately recruited... that is, they are refractory to recruitment when they are generated. 

The easiest way to do this so to create a new compartment, $P_{r}$ which are newly generated quiescent plasma cells that differentiate into inducible cells on a longer time scale (longer than the timescale of an infection). $P_s$ will produce $P_r$ at a rate $k_1$, $P_r$ will differentiate into $P_q$ at a rate $k_2$, and $P_q$ will differentiate back into $P_s$ at a rate $k_{-1}$ during infections. 

This would give the following change to our ODEs: 


$$
\frac{dB}{dt} = r_B(1-f)BV -fBV
$$

$$
\frac{dP_s}{dt} = fBV - k_1P_s - d_\mu P_s + k_{-1}P_qV
$$

$$
\frac{dP_r}{dt} = k_1P_s - k_2P_r - d_qP_r
$$

$$
\frac{dP_q}{dt} = k_2P_r - k_{-1}P_qV - d_qP_q
$$

where 

$$
V(t) = 
\begin{cases}
0 & \text{if } t > t_{infection} \\
1 & \text{if } 0 < t \leq t_{infection}
\end{cases}
$$

I am not going to do this now, but keep this option open in the future, Cora!

# Antibody production and competition for transport

We would like to observe the speed of recall responses compared to primary responses in terms of the amount of specific antibody transported to the mucosa. So, I need to track the specific antibody produced in the mucosa, the rate at which it is transported in the lumen (complete with competition from pre-existing Abs), and the dynamics of lumenal Abs. I will compare the dynamics of $L_s$ increase during primary and secondary infections. 

We will use the same model for competition of antibody titers as in part 1. Briefly, this model assumes michaelis-mentin dynamics, and the flux of specific IgA into the lumen is given by $\frac{V_{max}}{K + M_s + M_{ns}}M_s$. Given some decay rate of antibody in the lumen, the differential equation for $L_s$ becomes: 

$$
\frac{dL_s}{dt} = \frac{V_{max}}{K + M_s + M_{ns}}M_s - d_L L_s
$$

While we pre-defined the kinetics of increase and decrease of $M_s$ in part 1, we are explicitly modeling the dynamics of the population of cells - $P_s$ - that secrete $M_s$. The rate of change of $M_s$ will thus follow: 

$$
\frac{dM_s}{dt} = \rho P_s - \frac{V_{max}}{K + M_s + M_{ns}}M_s - d_AM_s
$$
where $\rho$ is the production rate of antibodies per plasma cell and $d_A$ is the decay rate of IgA antibodies in the mucosa (half life on the order of days).
