---
title: "Evolutionary Constraints on the Longevity of IgA Antibody Titers"
subtitle: "Simulations Part 1: constraint on the longevity of antibody titers in the respiratory mucosa"
format: html
---

```{r setup}
#install.package("here")
library(here)

#install.package("ggplot2")
library(ggplot2)

#install.package("gridExtra")
library(gridExtra)

#install.packages("tidyverse")
library(tidyverse)

#install.packages("deSolve")
library(deSolve)

#load functions
source(here("code", "functions", "functions.R")) #loads functions from functions file

#choose plotting colors
my_colors = c("darkred", "maroon", "darkblue", "darkslategrey", "forestgreen", "darkorange", "goldenrod") #choose color range
num_colors = length(my_colors) #set number of colors needed for plotting
my_colors = colorRampPalette(my_colors)(num_colors) #increase number of colors staying in color range
```
# objective

The purpose of this document is to help me determine the right parameter ranges to use

# Antibody titers

Below, we can see how the steady-state nonspecific antibody titer compares to the antibodies generated during a response. 

```{r antibodies}
#parms for antibodies
t_half = c(7, 14, 30, 60, 180, 365, 5*365) #half livesof antibody titers in days
## for steady state Mns
  c = 0.5 #constant rate of IgA generated through time, per day
  d_mus = -log(1/2)/(t_half) #decay rate of antibody in the mucosa (1/days)
## for newly generated Ms
  A0 = 10^2
  r = log(10^5)/14 #exponential growth of new population
  t_p = 7 #1/2 time to peak (days)
  
  
#### Mucosal nonspecific
# Calculate ss concentrations of Mns
M_ns.vec = sapply(d_mus, function(d_mu) {M_ns(c = c, d = d_mu)})

# plot 
plot(x = t_half/365, y = log10(M_ns.vec), type = "b", pch = 19, xlab = expression(paste("T"[1/2], " mucosal antibody titers (years)")), ylab = expression(paste("Log"[10], " Total ", "M"[ns])), main = "Steady state mucosal antibody titer by half-life")

#create df to store d_mu, M_ns, and t_half 
M_ns.df = data.frame( "t_half" = t_half,  #half life
                      "d_mu" = d_mus, #corresponding decay rate
                      "M_ns" = M_ns.vec) #corresponding ss antibody titer

# dynamics of antibody responses over course of infection
#specific antibodies during infection
M_s = function(A0, t_p, r, d_mu, t) {(A0/(1+exp(-r*(t-t_p))))*(1/(1+exp(-d_mu*(2*t_p-t))))} #sigmoidal growth, A0 is max antibody, t_p is half the time to peak, r is initial growt


t = seq(0,4*t_p, by = 1/24)

m_trajectories = sapply(d_mus, function(d_mu){
  ms = sapply(t, function(time) {M_s(A0 = A0, t_p = t_p, r = r, d_mu = d_mu, t = time)})
}) %>% cbind(t, .) %>% as.data.frame()
  
colnames(m_trajectories) = c("time", t_half)

m_trajectories = m_trajectories %>% 
  pivot_longer(
    cols = !time,
    names_to = "t_half",
    values_to = "titer"
  )

plot = ggplot() + geom_line(data = m_trajectories, aes(x = time, y = log10(titer), group = t_half, col = t_half)) +
  geom_hline(data = M_ns.df, aes(yintercept = log10(M_ns), col = factor(t_half))) +
  theme_classic() 

plot
```

lets plot our competition function so we can better understand the effect of changing k, vmax, and [antibody]. 

```{r plot-saturating-mm}
#define competition function
mm_flux = function(Abs, K, Vmax) {Abs*Vmax/(K + Abs)}

#define parms 
Abs_vec = 10^seq(0,3, 0.5)
K_vec = 10^seq(0,3, 0.5)
Vmax_vec = 2*10^seq(0,5, 1)

#plot different combos of v, k, and Abs
plot_dfs = lapply(Vmax_vec, function(Vmax){ #item in list
  df = sapply(K_vec, function(K){ #columns
         sapply(Abs_vec, function(Abs){ #rows
           return(mm_flux(Abs = Abs, K = K, Vmax = Vmax))
         })
       }) %>% cbind(Abs_vec, ., Vmax) %>% as.data.frame()
  colnames(df) = c("Ab", K_vec, "Vmax")
  return(df)
})

plot_list = lapply(plot_dfs, function(df){
  df = df %>% pivot_longer(
    cols = !c("Ab", "Vmax"),
    names_to = "K", 
    values_to = "flux"
  )
  plot = ggplot() + geom_line(data = df, aes(x = Ab, y = flux, group = as.factor(signif(as.numeric(K),2)), col = as.factor(signif(as.numeric(K),2)))) +
    geom_hline(yintercept = unique(df$Vmax), linetype = "dashed") +
    theme_bw() + 
    scale_color_manual(values = my_colors) +
    labs(x = "[Ab]", y = "flux", col = "K")
  return(plot)
})

#show plots on grid 
do.call(grid.arrange, plot_list)

```

